export enum GameEvents {
    NONE = 0,

    GAME_START = 10,
    LEVEL_COMPLETE,
    LEVEL_CHANGED,

    WORD_CORRECT = 20,
    WORD_INCORRECT,
    WORD_CHANGED,

    LETTER_HOVER = 30,
    LETTER_CHOSEN,
    LETTER_CANCELLED,

    INPUT_MOVE = 40,
    INPUT_END,
}